"""add role of user

Revision ID: ac0b2b998ed6
Revises: 2aff269b9c18
Create Date: 2023-06-22 16:51:31.769182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0b2b998ed6'
down_revision = '2aff269b9c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
