"""Init

Revision ID: d06e8774f1eb
Revises: d08ab3425555
Create Date: 2023-07-10 17:17:39.640218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06e8774f1eb'
down_revision = 'd08ab3425555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
